version: "3.8"

services:
  app:
    image: 1seyoung/unear-app:latest
    container_name: app-server
    expose:
      - "8080"
    networks:
      - backend

  nginx:
    image: nginx:stable
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - backend

networks:
  backend: