spring:
  jpa:
    open-in-view: false

  config:
    import:
      - optional:application-local.yml
      - optional:application-secret.yml
      - optional:application-docker.yml

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}




  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${oauth2.google.client-id}
            client-secret: ${oauth2.google.client-secret}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - email
              - profile

          kakao:
            client-id: ${oauth2.kakao.client-id}
            client-authentication-method: client_secret_post
            client-secret: ${oauth2.kakao.client-secret} # 필요 없다면 생략 가능
            client-name: Kakao
            provider: kakao
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope:
              - account_email
              - profile_nickname

        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth?prompt=select_account
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

springdoc:
  api-docs:
    path: /api/app/v3/api-docs
  swagger-ui:
    path: /api/app/swagger-ui.html
    config-url: /api/app/v3/api-docs/swagger-config
    url: /api/app/v3/api-docs