spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: seongbin3607@gmail.com
    password: "hswr eaju fhwv jois"  # 보안 앱 비밀번호
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true